### ISSUE TITLE
Static implementation? 

### ISSUE THREAD

**Issue by lazmo88** [kylephillips/favorites#101]
Heya, plugin seems exactly what we are looking for. Especially the cookie based cache part. 

I am wondering if this could be used on a static website or does it always require php? If yes, could it be possible to point the code to a custom backend server/WP instance to facilitate the Ajax requests and save the data there?

**Comment by bencorke** [comment]
Would be easier to port the static site to WordPress I would imagine.

**Comment by kylephillips** [comment]
This plugin does require WordPress/PHP. There are plans to add WP API support, but due to the use of sessions/cookies/authenticated user ids as part of the core of the plugin, I'm not sure it will fit your requirements.
