### ISSUE TITLE
Infinite scroll

### ISSUE THREAD

**Issue by bencorke** [kylephillips/favorites#102]
I'm using Algolia hosted search with infinite scroll for pagination of results, it's purely JS. New result favorite buttons are not updated.

1. Is there an easy JS method to update favorite statuses, in my callback, after new results are loaded?
2. I also need to ensure AJAX data requests have finished loading before running the favorites data functions.

Thanks,
Ben

**Comment by bencorke** [comment]
Solved with:` jQuery(document).trigger('favorites-update-all-buttons');`

**Comment by artifex-media** [comment]
> jQuery(document).trigger('favorites-update-all-buttons');

Live saver! Just sent an support email explaning the exact same issue, as I could not find anything related in the documentations.

Fixed my problem as well, perfect!
