### ISSUE TITLE
If else syntax doesn't work when checking favorites count by post

### ISSUE THREAD

**Issue by dennop** [kylephillips/favorites#105]
Hi @kylephillips 
I wanted to display different message depending on the favorites count on _single.php_ template,

````
<?php  if ( get_favorites_count() < 5 ) { ?>
// show something
<?php } if ( get_favorites_count() >= 5 ) { ?>
// show something else
<?php } ?>
````
Unfortunately, it didn't work. Please help me.
Also, I tried to put back the _$post_id_, still it cannot check the condition successfully.

**Comment by kylephillips** [comment]
The "get_favorites_count" function returns the count, wrapped in a span tag with data attributes necessary for ajax functionality.

With what you're trying to do, you'll need to specify the html parameter as false (3rd param).

Try this:

`<?php
$favorites_count = get_favorites_count($post_id = null, $site_id = null, false);
if ( intval($favorites_count) < 5 ){
	// Show Something
} else {
	// Show Something Else
}`
