### ISSUE TITLE
Add option to (shortcode to) remove item from Favorites on User fav page

### ISSUE THREAD

**Issue by enoversum** [kylephillips/favorites#25]
Hi there,

it would be 100% helpful if you made it possible to remove single entries from a user’s favorites list - or clear it once and for all. That would make this plugin even more awesome :wink: .

**Comment by kylephillips** [comment]
Rolling this into these 2 enhancements:
https://github.com/kylephillips/favorites/issues/27
https://github.com/kylephillips/favorites/issues/28

**Comment by enoversum** [comment]
Will it also include single item deletion, or only all at once (i.e. reset)?
