### ISSUE TITLE
JavaScript Callback Functions

### ISSUE THREAD

**Issue by shefik** [kylephillips/favorites#35]
What is the proper way to use the JavaScript callback functions?

You already have them defined in the minified JavaScript file. Are you wanting us to modify that file directly?

Also, the documentation here seems incorrect, where you reference "simple-locator", under "Callback Functions":

https://favoriteposts.com

**Comment by bluantinoo** [comment]
@shefik I got your same question. Did you figure it out? Editing plugin core files does no seems right, but if not, what?

**Comment by kylephillips** [comment]
The new version will deprecate the old callback functions in favor of custom events.

If you're using jQuery, this will simplify things.

For example, to complete something after a favorite has been saved, the new "favorites-updated-single" event can be used:

`$(document).on('favorites-updated-single', function(event, favorites_array, post_id, site_id, status){
 // Do stuff here, use the parameters as needed
});`

I will update the plugin documentation with the new events.
