### ISSUE TITLE
[Suggestion] Replace favorites with lists

### ISSUE THREAD

**Issue by fbg13** [kylephillips/favorites#36]
Basically instead of favoring a post the user adds it to a list (could be favorites, bookmarks, read later etc),  maybe the user could create this "lists" (like youtube) or they are created by the admin.

Would this be viable at this point?

**Comment by renatonascalves** [comment]
I might be wrong, but I guess this is possible fetching with `get_user_favorites_list()` ?

**Comment by kylephillips** [comment]
I'm closing this issue… I'm building out a "pro" version of the plugin that this will be available in.
