### ISSUE TITLE
Add filter to generated list

### ISSUE THREAD

**Issue by kylephillips** [kylephillips/favorites#38]
Add filter to the generated list, which will let devs format however they need to without a custom query. Will also solve AJAX problem.

**Comment by slimndap** [comment]
I went a ahead and added a solution for what I was trying to achieve.

One problem I still see is that the `[user_favorite_count]` shortcode is using two different ways to get the favorites. The client side is using `UserRepository::getAllFavorites()``, while AJAX is using `UserRepository::getFavorites()`.

**Comment by kylephillips** [comment]
The list code has been rewritten on the front and back end, with multiple filters added for customization. These will be added to the plugin website documentation.

The above PR hasn't been affected.
