### ISSUE TITLE
Using filters not working

### ISSUE THREAD

**Issue by d3haynes** [kylephillips/favorites#42]
passing a post type into any of the retrieval functions always displays ALL of the post ID's that have been favorited for that user.

**Comment by d3haynes** [comment]
for example:

    $solutions   = get_user_favorites($user_id = null, $site_id = null,$filters = array('post_type' => 'solutions'));

gives me the same ID's as 

    $tips        = get_user_favorites($user_id = null, $site_id = null,$filters = array('post_type' => 'tips_trends'));

**Comment by d3haynes** [comment]
Disregard, apologies. Didn't read that I had to pass it an array of post types lol

**Comment by Pieter12** [comment]
Hello d3haynes, 

Could you possibly share an example for your solution. I'm running into the same problem and cant seem to find the right syntax to get the filter to work. I'm trying to filter to just a post type.

Thanks!

Pieter
