### ISSUE TITLE
SimpleFavorites\Bootstrap::startSession consumes a lot of time

### ISSUE THREAD

**Issue by alanzchen** [kylephillips/favorites#43]
`SimpleFavorites\Bootstrap::startSession` slows down the page for almost 898 ms at index.php of the WordPress.

I haven't read the code yet, but I use cookie instead of session to store the metadata. I guess `startSession` here means using session to store the metadata?

Please let me know if I can help with debugging.

**Comment by johnmontfx** [comment]
I'm curious if you tracked this down, as I'm experiencing the same thing. I've been checking out the code and adding traces but I'm not very familiar with the Bootstrap process.

Thanks for any insights...
