### ISSUE TITLE
get count of favorites, across all posts

### ISSUE THREAD

**Issue by derickbailey** [kylephillips/favorites#49]
i'm integrating Favorites into my site at watchmecode.net and i'm loving it so far!

now i'm trying to build a little vanity metric on my WP Dashboard, to show me the total number of favorites added by all users, but I can't find a way to do this easily.

i could loop through all posts, call `get_users_who_favorited_post`, loop through those and add +1 per favorite, but that's going to be a ton of processing and loops for a large list of posts / taxonomies.

it would be nice to have a `get_all_favorites` or something like that, where i can get a list or count of all favorites in the system

thanks for the great plugin!

**Comment by renatonascalves** [comment]
I'd like some ideas of how to improve this. This is how I was able to get all this information so far:

`function get_all_favorites( $post_type = 'post', $posts_per_page = 100, $output = false ) {
	$query = new WP_Query(
		array(
			'post_type'              => $post_type, // Accepts an array of posts, array( 'posts', 'page')
			'post_status'            => 'publish',
			'meta_key' 		=> 'simplefavorites_count',
			'posts_per_page'     => $posts_per_page,
			'cache_results'         => true,
			'update_post_term_cache' => false
		)
	);

	// Return nothing if it's null
    if ( is_null( $query ) ) {
        return;
    }

    $count = array();
    foreach ( $query as $q ) {
    	$count[] = get_post_meta( $q->ID, 'simplefavorites_count', true );
    }

	return ( $output == true ) ? (int) count( $count ) : $count;
}`

Indeed, for large sites this is not suitable, I guess. 

Anyone has any thoughts on how we could approach this with Favorites?
