### ISSUE TITLE
TypeError: t.userfavorites is undefined

### ISSUE THREAD

**Issue by bluantinoo** [kylephillips/favorites#59]
I tried latest github version and I got this error when removing a favorite using the button generated by the shortcode.

**Comment by jer0dh** [comment]
Don't know if this is related or not, but I got the same error message on page load  where I had added the favorites button using a shortcode but also running it through the wp_kses_post filter.  I didn't realize that the wp_kses_post filter stripped out the data-postid and other data attributes from the button element.

**Comment by kylephillips** [comment]
I'm unable to reproduce this error.

If you're pulling from this repo, make sure you run composer install, install the npm dependencies and compile the assets using the included gulpfile.
