### ISSUE TITLE
Would love support for favoriting users/authors

### ISSUE THREAD

**Issue by JiveDig** [kylephillips/favorites#6]
I'm using a custom version of https://pippinsplugins.com/series/creating-a-user-follow-system-plugin/ for a project I'm working on now. WP Favorites would help me minimize code if I could add similar functionality for users. It's basically a "Follow" button like twitter/facebook. If I 'favorite' a user, I can then use a template tag or build a custom query to show latest posts/post_type of the authors I follow.  Or anything for that matter.

My current system works well, just curious of the idea to add it to your amazing looking plugin.

**Comment by kylephillips** [comment]
User support is definitely next on the punch list of features.

**Comment by duongancol** [comment]
Interesting feature! :+1:

**Comment by kylephillips** [comment]
I'm closing this issue… I'm moving this to a "pro" version of the plugin currently in progress.

**Comment by JiveDig** [comment]
Hey @kylephillips is this still a thing? Ran into a situation where having the ability to favorite comments and comment authors would be super useful. A pro version would be super powerful if it just provided an API to store/retrieve favorited pieces of content, and the devs can decide what/where that content comes from. Just curious if you were still pursuing a pro version.
