### ISSUE TITLE
[Suggestions] 'Transport' Favs from 'Anonymous' to profile & extra notice popup

### ISSUE THREAD

**Issue by shenom-x** [kylephillips/favorites#62]
Hi.

Great progress with great new features at the last weeks - Thank You! Will check the excerpt and thumbnail function today.

1) Any chance to 'transport' the Favs from 'Anonymous Users' cookies / session to 'Signed in User' - after the registeration / login process - 'automaticly'? Here is the case : The user browse - markes some Favs and now he/she do a registration or a login. Would be super deluxe if the Favs then jump over to the user profile and don´t get lost with a kill of the browser temp files.

2) The second would be something in between whats now possible. An 'Anonymous Users' can check the Favs - but the first hit it would bring up a popup to inform and give the possibility to do a registration immediatly.

**Comment by renatonascalves** [comment]
1. That might be tricky, I guess. There are several ways site can register a user on WordPress. Several forms, plugins, etc. Maybe something can be hooked on user_register but still.

**Comment by shenom-x** [comment]
I guess - You are right! :) We're also using the 'WP User Manager' - which enhance the registration / login process with the DoubleOptIn function, etc. very well.

But guess how smart this would be! At the end You could fire the user a message with something like that 'Your temporarily stored Favorites are now safely droped in Your profile - enjoy!'

**Comment by renatonascalves** [comment]
Indeed! I think this is possible... Counts, even for anonymous users are stored in the database... I guess it is possible to hook into the WordPress register hook and apply the current anonymous counts for the new created user.

I don't see a reason to "tell the user" that the information is being transferred. But user cases where it does might exist.

What do you think about it @kylephillips?

**Comment by kylephillips** [comment]
I'm going to close this issue… I'm planning on incorporating something similar in a "pro" version currently under development.
