### ISSUE TITLE
Filter issue in Dependencies.php

### ISSUE THREAD

**Issue by bobalbert** [kylephillips/favorites#64]
In wp-content/plugins/favorites/app/Activation/Dependencies.php on line 115 you have an apply_filter for the auth popup I assume so folks can change the wording and/or look etc.

But the apply_filters is on 'the_content" which I think is wrong. That should be reserved for post content. 

We are using shopplugin which relies heavily on the "the_content" filter for it's templating and favorites plugin is breaking it.

Shouldn't that actually be named something for the plugin like:
`'authentication_modal_content' => apply_filters(''favorites_auth_modal'', $this->settings_repo->authenticationModalContent() )`

**Comment by kylephillips** [comment]
There is a custom filter for the modal content, but the content filter is used to parse and display the contents of the auth modal WYSIWYG field. There are some problems introduced by using that filter that I thought were solved.

I'm replacing the use with a plugin function that runs the same filters as the_content.
