### ISSUE TITLE
favorites/button/html filtering problem

### ISSUE THREAD

**Issue by yasinaltintas** [kylephillips/favorites#66]
Hello

I am trying to use a filter function as stated on the documentation

`
add_filter( 'favorites/button/html', 'custom_favorites_button_html', 10, 4 );
function custom_favorites_button_html($html, $post_id, $favorited, $site_id){

        $html .= '<span class="icon-heart"></span>'.get_favorites_count(get_the_ID());

    return $html;
}`

After favoriting a post it removes my custom code from the spinnet. Also i tried with favorites/button/text/active and not worked.

**Comment by kylephillips** [comment]
I'm pushing up a change, but the unfortunately the post id will not be available as a parameter on sites with cache enabled.

Rather than using the count function, if you include an empty span with a class of `simplefavorite-button-count`, it will populate automatically (after the next update)

**Comment by yasinaltintas** [comment]
Thanks for informing i will be waiting for the new update!
