### ISSUE TITLE
Programmatically add new Favorite

### ISSUE THREAD

**Issue by stevenquinn** [kylephillips/favorites#67]
@kylephillips is there a way to programmatically add a new favorite? I'm looking for something like ```set_user_favorite($post_id, $user_id = NULL)```?

**Comment by kylephillips** [comment]
Not currently.

**Comment by scharc** [comment]
Is it still not possible? I would love a solution to favorite stuff for my customers... 

My solution right now is to log in to the customer account and do it there manually
