### ISSUE TITLE
Support for multiple buttons? e.g; like, save for later, etc

### ISSUE THREAD

**Issue by mishtershmart** [kylephillips/favorites#68]
Howdy,

Loving the look of this plugin. We have a need to have both a 'like' functionality and also a 'save for later', so I'm curious if this plugin can support and differentiate between multiple buttons? 

Cheers!
Phil

**Comment by kylephillips** [comment]
It kind of depends.

If you're wanting to save 2 different states for the same post, then no… it doesn't currently do that. There is a pro version in development that will, but I don't have a date as to when that will be available.

If there are 2 different post types that you're wanting to be able to "save", then yes. You could use the hooks provided by the plugin to customize the button text based on what the post type is.

**Comment by catalin88** [comment]
:( still not available

**Comment by tripod3d** [comment]
Any updates on this?
