### ISSUE TITLE
Favorite category?

### ISSUE THREAD

**Issue by heroickoala** [kylephillips/favorites#74]
Hi! 

I like the plugin. I was wondering if it would be possible to favorite a category instead of a post? Like that the user could see the latest post of a favorite category on a specific page? A bit like a subscribe button. 
Do you think it could be possible to do that based on the plugin? 

Thanks!

**Comment by kylephillips** [comment]
It's not currently possible to mark anything other than posts as favorites. I have a pro version under development where this feature is in the works.
