### ISSUE TITLE
Share with friend list of Favorite Posts

### ISSUE THREAD

**Issue by amerezhko** [kylephillips/favorites#76]
Hey there,
First of all, I want to thank the developers of the plugin!

**Question:** Is such a function planned?
**Function:** Share your favorite collection of posts with your friends by generating a unique link.
**Example:** mysite.com/favorite/?share=e21917bf12234c034f1a1b18a5631f0c

Thank you!

**Comment by kylephillips** [comment]
This functionality is not planned.
