### ISSUE TITLE
How can I add pagination

### ISSUE THREAD

**Issue by mohammad983** [kylephillips/favorites#87]
Hi
How can I add pagination in my user favorite lists?

**Comment by CHEWX** [comment]
Hi, You could do this — https://github.com/kylephillips/favorites/issues/81

**Comment by mohammad983** [comment]
its not page number. its 'show more'

**Comment by CHEWX** [comment]
@mohammad983 You could use the same technique. 

You need to hire a developer to do this for you, it's not possible within the plugin without custom code.
